POST http://localhost:8080/item
Content-Type: application/json

{
  "value": 10,
  "tag": "Foo"
}
###
PUT http://localhost:8080/item/64a578f6f8d099761a3f1875
Content-Type: application/json

{
  "tag": "Bar",
  "value": 5
}

###
PUT http://localhost:8080/item/64a6c96de28d6441cd5b8c9e
Content-Type: application/json

{
  "tag": "Bar",
  "value": 10
}

###
DELETE http://localhost:8080/item/64a6c96de28d6441cd5b8c9e

###
GET http://localhost:8080/item/64a6c96de28d6441cd5b8c9e

###
GET http://localhost:8080/item?orderBy=updatedAt&orderType=descendant

###
GET http://localhost:8080/item?value=5&operator=<

###
GET http://localhost:8080/item?tags=Foo

###
GET http://localhost:8080/item?value=10&tags=Foo&operator==

###
GET http://localhost:8080/item?orderBy=updatedAt&limit=2&page=1